name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: soma
      id: soma
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 2
        setup-command: pip3 install pytest
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SOMA_RESULTS: "${{steps.soma.outputs.result}}"
      with:
        runners: soma
